import type { Destination } from '@/types/content';

export const destinations: Destination[] = [
  { slug: 'bandung', name: 'Bandung', region: 'West Java', copy: { desktop: 'Dari Braga dan Dago hingga Lembang dan Ciwidey—atur perjalanan sesuai ritme Anda.', mobile: 'Lembang • Braga • Ciwidey' }, highlights: ['Lembang', 'Braga', 'Ciwidey'], image: '/images/editorial/destination-west-java.webp', recommendedVehicles: ['Toyota Innova Zenix Q', 'Toyota Hiace Premio'] },
  { slug: 'puncak', name: 'Puncak', region: 'Bogor', copy: { desktop: 'Weekend escape untuk keluarga dengan perjalanan private dan pilihan kelas kendaraan yang fleksibel.', mobile: 'Cisarua • Safari • Cibodas' }, highlights: ['Cisarua', 'Taman Safari', 'Cibodas'], image: '/images/editorial/destination-west-java.webp', recommendedVehicles: ['Toyota Innova Reborn', 'Toyota Fortuner GR'] },
  { slug: 'bogor', name: 'Bogor', region: 'West Java', copy: { desktop: 'City escape, kuliner, dan perjalanan keluarga ke Bogor dan Sentul.', mobile: 'Sentul • Kebun Raya • Kuliner' }, highlights: ['Sentul', 'Kebun Raya', 'Kuliner'], image: '/images/editorial/fleet-premium-mobility.webp', recommendedVehicles: ['Mitsubishi Xpander'] },
  { slug: 'anyer', name: 'Anyer', region: 'Banten', copy: { desktop: 'Coastal trip bersama keluarga atau sahabat dengan ruang yang sesuai kebutuhan perjalanan.', mobile: 'Beach • Family • Weekend' }, highlights: ['Beach', 'Family', 'Weekend'], image: '/images/editorial/destination-west-java.webp', recommendedVehicles: ['Toyota Avanza New', 'Toyota Hiace Premio'] },
  { slug: 'jakarta', name: 'Jakarta', region: 'DKI Jakarta', copy: { desktop: 'City tour, event, airport, dan aktivitas harian dalam satu layanan mobilitas.', mobile: 'City • Event • Airport' }, highlights: ['City Tour', 'Event', 'Airport'], image: '/images/editorial/fleet-premium-mobility.webp', recommendedVehicles: ['Toyota Alphard Gen 4 Hybrid', 'Toyota Innova Zenix Q'] },
];
